# -*- encoding: utf-8 -*-

raise "ruby 1.9 required" if RUBY_VERSION < '1.9'

MENU = {
  "Меню" => {
    "index.html" => "Главная",
    "work.html" => "Книги",
    "paper.html" => "Статьи",
    "diploma.html" => "Благодарности",
    "contact.html" => "Контакты",
    "guestbook" => "Книга мнений"
  },
  "Форум" => {
    "finvitation.html" => "Приглашение",
    "fdiscussions.html" => "Дискуссии",
    "fpeople.html" => "Персоналии",
    "forg.html" => "Орг. информация"
  },
  "Студенту" => {
    "student.html" => "&laquo;Заключения&raquo; дипломных работ",
    "student_presentation.html" => "Доклады на защите",
    "student_work.html" => "Науч. работа студентов",
    "practice.html" => "Произв. практика",
    "educational_process.html" => "Учебный процесс"
  },
  "Заметки" => {
    "conf2011.html" => 'Туризмоведение. Конференция 2011',
    "entrant.html" => 'Абитуриенту <span style="white-space: nowrap">о специальности</span> &laquo;Туризм&raquo;</a>',
    "newgen.html" => 'Новая генерация студентов'
  },
}

def generate_menu(path)
  res = "<!-- autogenerated by #{ $PROGRAM_NAME } -->"
  for top_level_name, items in MENU
    res << top_level_name << "\n"
    for item_path, item_name in items
      style = item_path == path.sub(".erb", "") ? ' style="color: Black;"' : ''
      item_path = "../#{ item_path }" if path =~ /work_item_template.erb.html/
      res << "<a href='#{ item_path }'#{ style }>#{ item_name }</a>" << "\n"
    end
  end
  res
end

Dir["*.html"].each do |path|
  src = nil
  File.open(path, "r:windows-1251:utf-8") do |file|
    src = file.read
  end

  menu_decoration = ['<div id="floatright">', '</div>']
  src.sub!(%r{#{menu_decoration[0]}.+?#{menu_decoration[1]}}m,
           menu_decoration[0] + generate_menu(path) + menu_decoration[1])

  File.open(path, "w:windows-1251:utf-8") do |out|
    out.write(src)
  end
end

