# -*- encoding: utf-8 -*-

raise "ruby 1.9 required" if RUBY_VERSION < '1.9'

MENU = {
  "Меню" => {
    "index.html" => "Главная",
    "work.html" => "Книги",
    "paper.html" => "Статьи",
    "diploma.html" => "Благодарности",
    "contact.html" => "Контакты",
    "guestbook" => "Книга мнений",
    "Книга мнений" => "Книга мнений",
    "entrant.html" => 'Абитуриенту <span style="white-space: nowrap">о специальности</span> &laquo;Туризм&raquo;</a>',
  },
  "Студенту" => {
    "student.html" => "&laquo;Заключения&raquo; дипломных работ",
    "student_presentation.html" => "Доклады на защите",
    "student_work.html" => "Науч. работа студентов",
  }
}

def generate_menu(path)
  res = "<!-- autogenerated by #{ $PROGRAM_NAME } -->"
  for top_level_name, items in MENU
    res << top_level_name << "\n"
    for item_path, item_name in items
      style = ' style="color: Black;"' if item_path == path
      res << "<a href='#{ item_path }'#{ style }>#{ item_name }</a>" << "\n"
    end
  end
  res
end

Dir["*.html"].each do |path|
  next if path =~ /work_item_template.erb.html/

  src = nil
  File.open(path, "r:windows-1251:utf-8") do |file|
    src = file.read
  end

  menu_decoration = ['<div id="floatright">', '</div>']
  src.sub!(%r{#{menu_decoration[0]}.+?#{menu_decoration[1]}}m,
           menu_decoration[0] + generate_menu(path) + menu_decoration[1])

  File.open("#{path}.out", "w:windows-1251:utf-8") do |out|
    out.write(src)
  end
  exit(0)
end

